import './globals.css'

import { Inter } from 'next/font/google'
import Footer from '../components/footer/Footer'
import NavBar from '../components/navbar/NavBar'
import { ClerkProvider } from '@clerk/nextjs'
// import { Providers } from "./providers";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            <div className="bg-background">
              <NavBar />
              {children}
              <Footer />
            </div>
          </body>
        </html>
    </ClerkProvider>
  )
}
